title: T Jota
logo: docs/assets/STM32_TouchGFX_SRHC04.png
description: Aspiring Software Engineer | Data Enthusiast
theme: jekyll-theme-primer
url: "https://tejotago.github.io"
social_links:
  linkedin: "https://linkedin.com/in/t14gom3s"
  kaggle: "https://www.kaggle.com/tejota"
  tableau: "https://public.tableau.com/app/profile/t.jota/vizzes"
